version: '3.7'

networks:
  acai:

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: postgres_acai
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgreSQL
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - acai

  acai-api:
    image: acai_api
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.test
    depends_on:
      - postgres
    networks:
      - acai
