"""empty message

Revision ID: a1b15ab82c9d
Revises: 
Create Date: 2020-03-08 10:53:04.431236

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1b15ab82c9d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum("choice", "personalization", "done", name="orderstage"),
            nullable=False,
        ),
        sa.Column(
            "size", sa.Enum("small", "medium", "big", name="ordersize"), nullable=False
        ),
        sa.Column(
            "flavor",
            sa.Enum("strawberry", "banana", "kiwi", name="orderflavor"),
            nullable=False,
        ),
        sa.Column(
            "personalization",
            sa.Enum(
                "granola", "peanut_candy", "ninho_milk", name="orderpersonalization"
            ),
            nullable=True,
        ),
        sa.Column("setup_time", sa.Time(), nullable=False),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
